In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


# Feature Scaling


In [2]:
df=pd.read_csv('downsampled.csv')
X=df.drop(labels='stimulus',axis=1)
y=df['stimulus']

In [3]:
from sklearn.decomposition import PCA
pca = PCA(n_components=35)



In [4]:
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents)

In [5]:
X=principalDf.copy()

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)



# Splitting Dataset

In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Principal Component Analysis

In [8]:
#from sklearn.decomposition import PCA
#pca_model= PCA(n_components=2)



In [9]:
#principalComponents_breast = pca_model.fit_transform(x)


# SVM

In [10]:
from sklearn.svm import SVC
svc_model = SVC()
svc_model.fit(X_train,y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [11]:
predictions = svc_model.predict(X_test)

In [12]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[924  24   6   4   1   4   4]
 [ 11 930   9   1   0   7   3]
 [  3   4 924  21   0   3  15]
 [  0  12  16 941   3   0   0]
 [  1   6   1  11 986   0   2]
 [  4  26   3   2   1 963   6]
 [  0   0   0   0   0   0 966]]


In [13]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.98      0.96      0.97       967
           2       0.93      0.97      0.95       961
           3       0.96      0.95      0.96       970
           4       0.96      0.97      0.96       972
           5       0.99      0.98      0.99      1007
           6       0.99      0.96      0.97      1005
           7       0.97      1.00      0.98       966

    accuracy                           0.97      6848
   macro avg       0.97      0.97      0.97      6848
weighted avg       0.97      0.97      0.97      6848



# SVM -GRID

In [14]:
from sklearn.model_selection import GridSearchCV

In [15]:
param_grid = {'C': [0.1,1, 10], 'gamma': [1,0.1,0.01],'kernel':('linear', 'rbf')} 

In [16]:

grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] C=0.1, gamma=1, kernel=linear ...................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


KeyboardInterrupt: 

In [ ]:
grid_predictions = grid.predict(X_test)


In [ ]:
print(confusion_matrix(y_test,grid_predictions))

In [ ]:
print(classification_report(y_test,grid_predictions))

In [ ]:
#import pickle
# save the model to disk
#filename = 'SVM-Grid.sav'
#pickle.dump(grid, open(filename, 'wb'))
 

In [ ]:
#filename2 = 'SVM.sav'
#pickle.dump(svc_model_model, open(filename2, 'wb'))

# |ANN

