In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
feat_1=pd.read_csv('TD.csv',header=None)
feat_1.columns=['TD_0','TD_1','TD_2','TD_3','TD_4','TD_5','TD_6','TD_7','TD_8','TD_9','stimulus']


In [ ]:
feat_1['stimulus'].value_counts()


In [ ]:
feat_2=pd.read_csv('IAV.csv', header=None)
feat_2.columns=['IAV_1','IAV_2','stimulus']

In [ ]:
feat_3=pd.read_csv('MAV.csv',header=None)
feat_3.columns=['MAV_1','MAV_2','stimulus']

In [ ]:
feat_4=pd.read_csv('mDWT.csv',header=None)
feat_4.columns=['dwt_1','dwt_2','dwt_3','dwt_4','dwt_5','dwt_6','dwt_7','dwt_8','stimulus']

In [ ]:
feat_5=pd.read_csv('rms.csv',header=None)
feat_5.columns=['rms_1','rms_2','stimulus']

In [ ]:
feat_6=pd.read_csv('ssc.csv',header=None)
feat_6.columns=['ssc_1','ssc_2','stimulus']

In [ ]:
feat_7=pd.read_csv('wl.csv',header=None)
feat_7.columns=['wl_1','wl_2','stimulus']

In [ ]:
feat_8=pd.read_csv('zc.csv',header=None)
feat_8.columns=['zc_1','zc_2','stimulus']

In [ ]:
truth=feat_8['stimulus']==feat_7['stimulus']
truth.value_counts()

In [ ]:
feat_9=pd.read_csv('HIST.csv',header=None)
l=[]
for i in range (1,43):
        name='HIST_'
        name=name+str(i)
        l.append(name)
l.append('stimulus')
feat_9.columns=l

In [ ]:
#81 columns
df=pd.concat([feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9],axis=1)


In [ ]:
#save as csv
df.to_csv('All+features.csv',index=False)

df=pd.read_csv('All+features.csv')

In [ ]:
#find all zeroes columns

cols=list(df.columns)
zeroes=[]
for i in cols:
    truth= (df[i] == 0).all()

    if (bool(truth.all())):
        zeroes.append(i)
    

In [ ]:
#drop all-zeroes columns
df.drop(labels=zeroes,axis=1,inplace=True)

In [ ]:
stimu=np.array(df['stimulus'])

In [ ]:
#remove repeated columns
stimu=np.array(df['stimulus'])
stimu=stimu.reshape((40844,1),)
cols_stim=['stimulus.1','stimulus.2','stimulus.3','stimulus.4','stimulus.5','stimulus.6','stimulus.7','stimulus.8']
df.drop(labels=cols_stim,axis=1,inplace=True)






In [ ]:
df['stimulus'].value_counts()

# Resampling 


In [ ]:
from sklearn.utils import resample


In [ ]:
df_5 = df[df.stimulus==5]
df_minority = df[df.stimulus==2]

df_1 = df[df.stimulus==1]
df_3 = df[df.stimulus==3]
df_4 = df[df.stimulus==4]
df_6 = df[df.stimulus==6]
df_7 = df[df.stimulus==7]



In [ ]:
# Downsample majority class
df_5_downsampled = resample(df_5, 
                                 replace=False,    # sample without replacement
                                 n_samples=4891,     # to match minority class
                                 random_state=123) # reproducible results
df_1_downsampled = resample(df_1, 
                                 replace=False,    # sample without replacement
                                 n_samples=4891,     # to match minority class
                                 random_state=123) # reproducible results
df_3_downsampled = resample(df_3, 
                                 replace=False,    # sample without replacement
                                 n_samples=4891,     # to match minority class
                                 random_state=123) # reproducible results
df_4_downsampled = resample(df_4, 
                                 replace=False,    # sample without replacement
                                 n_samples=4891,     # to match minority class
                                 random_state=123) # reproducible results
df_6_downsampled = resample(df_6, 
                                 replace=False,    # sample without replacement
                                 n_samples=4891,     # to match minority class
                                 random_state=123) # reproducible results
df_7_downsampled = resample(df_7, 
                                 replace=False,    # sample without replacement
                                 n_samples=4891,     # to match minority class
                                 random_state=123) # reproducible results






 



In [ ]:
# Combine minority class with downsampled majority class
df_downsampled = pd.concat([df_1_downsampled,df_5_downsampled,df_3_downsampled,df_4_downsampled,df_minority,df_6_downsampled,df_7_downsampled ])

In [2]:
df_downsampled=pd.read_csv('downsampled.csv')

In [3]:
X=df_downsampled.drop(labels='stimulus',axis=1)
y=df_downsampled['stimulus']

# Feature Scaling


In [4]:
df=pd.read_csv('downsampled.csv')
X=df.drop(labels='stimulus',axis=1)
y=df['stimulus']

In [5]:
from sklearn.decomposition import PCA
pca = PCA(n_components=35)



In [6]:
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents)

In [7]:
X=principalDf.copy()

In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)



# Splitting Dataset

In [9]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Principal Component Analysis

In [10]:
#from sklearn.decomposition import PCA
#pca_model= PCA(n_components=2)



In [11]:
#principalComponents_breast = pca_model.fit_transform(x)


# SVM

In [14]:
from sklearn.svm import SVC
svc_model = SVC()
svc_model.fit(X_train,y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [15]:
predictions = svc_model.predict(X_test)

In [16]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[924  24   6   4   1   4   4]
 [ 11 930   9   1   0   7   3]
 [  3   4 924  21   0   3  15]
 [  0  12  16 941   3   0   0]
 [  1   6   1  11 986   0   2]
 [  4  26   3   2   1 963   6]
 [  0   0   0   0   0   0 966]]


In [17]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.98      0.96      0.97       967
           2       0.93      0.97      0.95       961
           3       0.96      0.95      0.96       970
           4       0.96      0.97      0.96       972
           5       0.99      0.98      0.99      1007
           6       0.99      0.96      0.97      1005
           7       0.97      1.00      0.98       966

    accuracy                           0.97      6848
   macro avg       0.97      0.97      0.97      6848
weighted avg       0.97      0.97      0.97      6848



# SVM -GRID

In [18]:
from sklearn.model_selection import GridSearchCV

In [19]:
param_grid = {'C': [0.1,1, 10], 'gamma': [1,0.1,0.01],'kernel':('linear', 'rbf')} 

In [20]:

grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] C=0.1, gamma=1, kernel=linear ...................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .................... C=0.1, gamma=1, kernel=linear, total=   9.1s
[CV] C=0.1, gamma=1, kernel=linear ...................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    9.0s remaining:    0.0s


[CV] .................... C=0.1, gamma=1, kernel=linear, total=   8.8s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] .................... C=0.1, gamma=1, kernel=linear, total=   9.2s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] .................... C=0.1, gamma=1, kernel=linear, total=   9.1s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] .................... C=0.1, gamma=1, kernel=linear, total=   9.3s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] ....................... C=0.1, gamma=1, kernel=rbf, total=  51.1s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] ....................... C=0.1, gamma=1, kernel=rbf, total=  49.4s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] ....................... C=0.1, gamma=1, kernel=rbf, total=  52.7s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .

[CV] ...................... C=1, gamma=0.01, kernel=rbf, total=  14.0s
[CV] C=10, gamma=1, kernel=linear ....................................
[CV] ..................... C=10, gamma=1, kernel=linear, total=  59.4s
[CV] C=10, gamma=1, kernel=linear ....................................
[CV] ..................... C=10, gamma=1, kernel=linear, total=  59.6s
[CV] C=10, gamma=1, kernel=linear ....................................
[CV] ..................... C=10, gamma=1, kernel=linear, total=  58.8s
[CV] C=10, gamma=1, kernel=linear ....................................
[CV] ..................... C=10, gamma=1, kernel=linear, total= 1.1min
[CV] C=10, gamma=1, kernel=linear ....................................
[CV] ..................... C=10, gamma=1, kernel=linear, total= 1.0min
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........................ C=10, gamma=1, kernel=rbf, total=  59.1s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] .

[Parallel(n_jobs=1)]: Done  90 out of  90 | elapsed: 48.8min finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10], 'gamma': [1, 0.1, 0.01],
                         'kernel': ('linear', 'rbf')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=2)

In [21]:
grid_predictions = grid.predict(X_test)


In [22]:
print(confusion_matrix(y_test,grid_predictions))

[[ 955    0    0    0   11    1    0]
 [   0  951    0    0    9    1    0]
 [   0    0  960    0   10    0    0]
 [   0    0    0  948   24    0    0]
 [   0    1    0    0 1006    0    0]
 [   0    0    0    1   17  987    0]
 [   0    0    0    0    0    0  966]]


In [23]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

           1       1.00      0.99      0.99       967
           2       1.00      0.99      0.99       961
           3       1.00      0.99      0.99       970
           4       1.00      0.98      0.99       972
           5       0.93      1.00      0.97      1007
           6       1.00      0.98      0.99      1005
           7       1.00      1.00      1.00       966

    accuracy                           0.99      6848
   macro avg       0.99      0.99      0.99      6848
weighted avg       0.99      0.99      0.99      6848



In [ ]:
#import pickle
# save the model to disk
#filename = 'SVM-Grid.sav'
#pickle.dump(grid, open(filename, 'wb'))
 

In [ ]:
#filename2 = 'SVM.sav'
#pickle.dump(svc_model_model, open(filename2, 'wb'))

# |ANN

